VIA_ENABLE = yes
#CONSOLE_ENABLE = yes
#MOUSEKEY_ENABLE = no
#WIRELESS_NKRO_ENABLE = no
#BLUETOOTH_NKRO_ENABLE = no
#NKRO_ENABLE = no
#EXTRAKEY_ENABLE = no

# Enable macros
EMACS_BUFFERSWITCHER_ENABLE = yes
EMACS_COMMENTING_ENABLE = yes
